CREATE TABLE Region
(
   Id INTEGER PRIMARY KEY,
   Name VARCHAR(200) NOT NULL
);

CREATE TABLE City
(
   Id INTEGER PRIMARY KEY,
   Name VARCHAR(200) NOT NULL,
   RegionId INTEGER,
   FOREIGN KEY (RegionId) REFERENCES Region(Id)
);

CREATE TABLE Citizen
(
   Id INTEGER PRIMARY KEY,
   FirstName VARCHAR(100) NOT NULL,
   LastName VARCHAR(100) NOT NULL,
   Age INTEGER NOT NULL,
   Sex INTEGER NOT NULL,
   CityId INTEGER NOT NULL,
   FOREIGN KEY (CityId) REFERENCES City(Id)
);